@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@url = http://{{host}}/api/users

### Register an user
POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "sakha",
    "email": "sakha@gmail.com",
    "password": "sakha"
}

### Login an user
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "sakha",
    "password": "sakha"
}

### Logout an user
POST {{url}}/logout HTTP/1.1

### Me 
GET {{url}} HTTP/1.1