@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@url = http://{{host}}/api/posts

### Get all posts
GET {{url}} HTTP/1.1

### Get post by ID 
GET {{url}}/1 HTTP/1.1

### Create a post
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "title": "hello bunga"
}

### Update a post by ID
PATCH  {{url}}/3 HTTP/1.1
Content-Type: application/json

{
    "title": "hello sakha"
}

### Delete a post by ID
DELETE {{url}}/3 HTTP/1.1